# Generated by Django 6.0.6 on 2026-08-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="instructorprofile",
            name="expertise",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="instructorprofile",
            name="qualification",
            field=models.TextField(blank=True),
        ),
    ]
